spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        messages-in:
          destination: greetings
          contentType: application/json
        messages-out:
          destination: greetings
          contentType: application/json