/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.brightonsbox;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.assertEquals;

public class MainTest {
    @Test public void testAppHasAGreeting() {
        Main classUnderTest = new Main();
        assertEquals("Hello world.", classUnderTest.getGreeting());
    }
}
