/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.brightonsbox;


import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class MainTest {

    @Test
    public void testAppHasAGreeting() {

        Main classUnderTest = new Main();

        assertThat(classUnderTest.getGreeting()).isEqualTo("Hello world.");
    }
}
